services:
  jukebox:
    build:
      context: .
      args:
        - BACKEND_HASH=$(find go -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)
        - FRONTEND_HASH=$(find frontend-react -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1)
    container_name: navidrome-jukebox
    network_mode: host
    env_file:
      - .env
    volumes:
      - jukebox_data:/data
    restart: unless-stopped

volumes:
  jukebox_data:
